
# ──────────────────────────────
#   FONT
# ──────────────────────────────

font_family      JetBrainsMono Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size 13

# ──────────────────────────────
#   WINDOW BEHAVIOR
# ──────────────────────────────

window_padding_width 8
enable_audio_bell no
remember_window_size no
placement_strategy center
hide_window_decorations titlebar-only

# ──────────────────────────────
#   PERFORMANCE
# ──────────────────────────────

repaint_delay 10
input_delay   1
sync_to_monitor yes

# ──────────────────────────────
#   SCROLLBACK
# ──────────────────────────────

scrollback_lines 5000
scrollback_pager_history_size 64

# ──────────────────────────────
#   KEYBINDINGS
# ──────────────────────────────

map ctrl+shift+backspace     close_tab
map ctrl+shift+enter new_tab
map ctrl+shift+h  previous_tab
map ctrl+shift+l next_tab

map ctrl+shift+o launch --type=tab --cwd=current
map ctrl+shift+p launch --type=tab --cwd=current nvim .


background_opacity    0.93

window_border_width 0
cursor_shape block
cursor_blink_interval 0
shell_integration enabled
cursor_trail 10
cursor_trail_decay 0.1 0.3
cursor_trail_start_thicken 0

confirm_os_window_close 0

# kitty tabs
bell_on_tab             yes
tab_bar_edge            bottom
tab_title_template      {title.split('/')[-1]}
focus_follows_mouse     yes
active_tab_font_style   italic
inactive_tab_font_style normal
# tab_bar_margin_width 10.0
# tab_bar_margin_height 10.0 0.0
tab_switch_strategy previous

# splits 
enabled_layouts splits
map ctrl+alt+v launch --location=vsplit --cwd=current
map ctrl+alt+left neighboring_window left
map ctrl+alt+right neighboring_window right
# Fechar o split atual com um atalho customizado
map ctrl+shift+x close_window


# BEGIN_KITTY_THEME
# Osaka Jade
# include gruvbox-dh-theme.conf
include gruvbox-dh-theme.conf
# include gruvbox-dh-theme.conf
# include gruvbox-dh-theme.conf
# END_KITTY_THEME
