preload =~/home/pedro/Pictures/arch.png

wallpaper {
    monitor = eDP-1
    path = /home/pedro/Pictures/arch.png
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/pedro/Pictures/arch.png
}
splash = false
