# Configurações Gerais
grab_focus = true

# Localizadores (Finders)
default_finder = desktop      # Abre buscando aplicativos por padrão
math_prefix = =               # Digitar "= 2+2" calcula automaticamente
unicode_prefix = .            # Digitar ". heart" busca emojis/caracteres
font_prefix = '               # Busca fontes do sistema

# Interface Visual (Ajuste o tamanho se achar necessário)
window_size = 720 560

# No seu hyprlauncher.conf
style_path = ~/.config/hypr/hyprlauncher.css

# ~/.config/hypr/hyprlauncher.conf

# Mostrar ícones dos aplicativos?
show_icons = true
icon_theme = "Papirus-Dark" # Altere para o seu tema de ícones instalado

# Configurações de exibição
max_results = 6              # Limita a lista para não ocupar a tela toda
sorting_mode = frequency     # Mostra os apps que você mais usa no topo!

# customizar as mensagens de espaço reservado (placeholder)
placeholder_text = Procure por algo ou use '=' para contas...
