input {
    kb_layout = us,br
    kb_options = compose:caps,grp:ctrls_toggle

    follow_mouse = 1
    
    sensitivity = 0

    # mais tarde configurar melhorar
    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

