windowrule {
    name = suppress-maximize-events
    match:class = .*

    # supress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyperland-run
    match:class = hyperland-run
    move = 20 monitor_h-120
    float = yes
}


# Regra moderna e direta para a classe do terminal
windowrule {
    name = bluetui -e bluetui
    match:class = bluetui -e bluetui
    float = yes

}

windowrule {
    name = float-satty
    match:class = com.gabm.satty
    float = yes
}

# Regras para o Wofi ficar estável

# windowrule {
#    name = wofi --show drun
#    match:class = wofi --show drun
#    float = yes
# }
