# Autostart necessary process or execute my fav apps at lunch
exec-once = waybar
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = hyprpaper
exec-once = hypridle
# exec-once = hyprpaper
exec-once = awww-daemon
# Inicializa o agente de autenticação
exec-once = hyprpolkitagent
#exec-onde = ~/.config/waybar/scripts/launch.sh
