# looknfeel

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    # allow_tearing = false - realcionado a jogos, ver depois isso
    
    # koda
    # col.active_border= rgba(FFFFFFaa)
    # col.inactive_border = rgba(595959aa)

    # tokyo night
    col.active_border = rgba(3b4261ff)
    col.inactive_border = rgba(0a0b0fcc)
    layout = dwindle

    resize_on_border = false

    # allow_tearing = false
}

decoration {
    rounding = 19
    rounding_power = 13

    active_opacity = 0.93
    inactive_opacity = 0.90


    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.15

    # blur {
    #     # old configs
    #     # enabled = true
    #     # size = 2
    #     # passes = 2
    #     # special = true
    #     # brightness = 0.60
    #     # contrast = 0.75
    #
    #     # new
    #     enabled = true
    #     size = 6
    #     passes = 2
    #     vibrancy = 0.2
    #     vibrancy_darkness = 1
    #     contrast = 0.9
    #     brightness = 0.7
    #     ignore_opacity = true
    #     noise = 0.05
    #
    #     # Otimização recomendada (opcional, mas ajuda na performance)
    #     new_optimizations = true
    # }

    blur {
        enabled = true
        size = 6 # Intensidade do desfoque (distância dos pixels)
        passes = 2 # Quantas vezes o filtro é aplicado (maior = mais suave/pesado)
        
        # Ajustes finos para efeito frosted-glass
        new_optimizations = true
        ignore_opacity = true # Garante que o blur ignore a opacidade da janela se necessário
        noise = 0.0117 # Adiciona uma textura leve de "papel"
        contrast = 0.8916 # Controla o nível de contraste do fundo
        brightness = 0.8172 # Controla o brilho atrás do vidro
        vibrancy = 0.1696 # Saturação das cores que passam pelo desfoque
        vibrancy_darkness = 1
    }

    shadow {
        enabled = true
        range = 2
        render_power = 3
        color = rgba(1a1a1aee)
    }

}

animations {
    enabled = true
    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92 
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = fluent_decel, 0.1, 1, 0, 1
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    animation = windows, 1, 3, md3_decel, popin 60%
    animation = border, 1, 10, default
    animation = fade, 1, 2.5, md3_decel
    animation = workspaces, 1, 3.5, easeOutExpo, slide
    animation = specialWorkspace, 1, 3, md3_decel, slidevert
}

dwindle {
    preserve_split = true
}

cursor {
    hide_on_key_press = true
    warp_on_change_workspace = 1
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false
}
